"""
Customer Segmentation Dashboard — Streamlit application.

Provides an interactive dark-themed UI for exploring RFM-based customer
segments generated by :mod:`rfm_analysis`.
"""

from __future__ import annotations

import os
from typing import Any

import pandas as pd
import streamlit as st
import plotly.graph_objects as go
import yaml

from constants import (
    NAVY, NAVY_CARD, NAVY_BORDER, WHITE, MUTED, GREEN, TEAL, BLUE, AMBER, RED,
    SEGMENT_COLORS as SEG_COLORS,
    SEGMENT_ORDER as SEG_ORDER,
    SEGMENT_ICONS as SEG_ICONS,
)

st.set_page_config(
    page_title="Customer Segmentation",
    page_icon="◈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Global CSS ────────────────────────────────────────────────────────────────
st.markdown(f"""
<style>
  @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@300;400;500;600&family=DM+Mono:wght@400;500&display=swap');

  html, body, [class*="css"] {{
    font-family: 'DM Sans', sans-serif;
    background-color: {NAVY};
    color: {WHITE};
  }}

  .stApp {{ background-color: {NAVY}; }}
  .block-container {{ padding: 2rem 2.5rem 3rem; max-width: 1400px; }}

  [data-testid="stSidebar"] {{
    background-color: {NAVY_CARD};
    border-right: 1px solid {NAVY_BORDER};
  }}
  [data-testid="stSidebar"] * {{ color: {WHITE} !important; }}
  [data-testid="stSidebar"] .stSelectbox label,
  [data-testid="stSidebar"] .stMultiSelect label {{
    color: {MUTED} !important;
    font-size: 0.72rem;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    font-weight: 500;
  }}

  .kpi-card {{
    background: {NAVY_CARD};
    border: 1px solid {NAVY_BORDER};
    border-radius: 10px;
    padding: 1.2rem 1.4rem;
  }}
  .kpi-label {{
    font-size: 0.72rem;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: {MUTED};
    font-weight: 500;
    margin-bottom: 0.35rem;
  }}
  .kpi-value {{
    font-size: 1.25rem;
    font-weight: 600;
    color: {WHITE};
    line-height: 1;
  }}
  .kpi-delta {{
    font-size: 0.78rem;
    margin-top: 0.4rem;
    color: {MUTED};
    font-family: 'DM Mono', monospace;
  }}
  .kpi-accent {{
    width: 28px;
    height: 3px;
    border-radius: 2px;
    margin-bottom: 0.8rem;
  }}

  .section-label {{
    font-size: 0.7rem;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: {MUTED};
    font-weight: 500;
    margin-bottom: 1rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid {NAVY_BORDER};
  }}

  .page-title {{
    font-size: 1.6rem;
    font-weight: 600;
    color: {WHITE};
    letter-spacing: -0.02em;
  }}
  .page-subtitle {{
    font-size: 0.85rem;
    color: {MUTED};
    margin-top: 0.2rem;
  }}

  .seg-badge {{
    display: inline-block;
    padding: 2px 10px;
    border-radius: 20px;
    font-size: 0.75rem;
    font-weight: 500;
    letter-spacing: 0.02em;
  }}

  [data-testid="stDataFrame"] {{
    border: 1px solid {NAVY_BORDER};
    border-radius: 8px;
    overflow: hidden;
  }}

  hr {{ border-color: {NAVY_BORDER}; margin: 1.5rem 0; }}

  .stTabs [data-baseweb="tab-list"] {{
    background: {NAVY_CARD};
    border-radius: 8px;
    border: 1px solid {NAVY_BORDER};
    padding: 3px;
    gap: 2px;
  }}
  .stTabs [data-baseweb="tab"] {{
    background: transparent;
    color: {MUTED};
    border-radius: 6px;
    font-size: 0.82rem;
    font-weight: 500;
    letter-spacing: 0.03em;
    padding: 6px 16px;
    border: none;
  }}
  .stTabs [aria-selected="true"] {{
    background: {NAVY_BORDER} !important;
    color: {WHITE} !important;
  }}

  [data-baseweb="tag"] {{
    background-color: {NAVY_BORDER} !important;
    color: {WHITE} !important;
  }}

  [data-baseweb="input"], [data-baseweb="select"] {{
    background-color: {NAVY_BORDER} !important;
    border-color: {NAVY_BORDER} !important;
    color: {WHITE} !important;
  }}

  [data-testid="stTextInput"] input {{
    color: {WHITE} !important;
    background-color: {NAVY_BORDER} !important;
  }}
  [data-testid="stTextInput"] input::placeholder {{
    color: {MUTED} !important;
    opacity: 1 !important;
  }}
  [data-testid="stTextInput"] label {{
    color: {MUTED} !important;
  }}

  ::-webkit-scrollbar {{ width: 4px; height: 4px; }}
  ::-webkit-scrollbar-track {{ background: {NAVY}; }}
  ::-webkit-scrollbar-thumb {{ background: {NAVY_BORDER}; border-radius: 4px; }}

  #MainMenu {{ display: none; }}
  footer {{ display: none; }}
  header[data-testid="stHeader"] {{ background: transparent; }}
  .stDeployButton {{ display: none; }}

  [data-testid="stSidebarCollapseButton"] {{
    visibility: visible !important;
    opacity: 1 !important;
    pointer-events: auto !important;
  }}

  [data-testid="stDownloadButton"] button {{
    background-color: {NAVY_CARD};
    color: {WHITE};
    border: 1px solid {NAVY_BORDER};
    border-radius: 8px;
    padding: 0.5rem 1rem;
    font-family: 'DM Sans', sans-serif;
    font-size: 0.85rem;
    transition: background-color 0.2s, border-color 0.2s;
  }}
  [data-testid="stDownloadButton"] button:hover {{
    background-color: {NAVY_BORDER};
    border-color: {MUTED};
    color: {WHITE};
  }}
  [data-testid="stDownloadButton"] button:active {{
    background-color: {NAVY_BORDER};
    color: {WHITE};
  }}
</style>
""", unsafe_allow_html=True)

# ── Plotly base layout ────────────────────────────────────────────────────────
PLOT_LAYOUT: dict[str, Any] = dict(
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(family="DM Sans", color=WHITE, size=12),
)

AXIS_DEFAULTS = dict(
    gridcolor=NAVY_BORDER, gridwidth=1,
    linecolor=NAVY_BORDER, tickcolor=NAVY_BORDER,
    zerolinecolor=NAVY_BORDER,
)


def hex_to_rgba(hex_color: str, alpha: float = 0.13) -> str:
    """Convert a hex colour to an rgba() CSS string."""
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"rgba({r},{g},{b},{alpha})"


# ── Data loading ──────────────────────────────────────────────────────────────
BASE_DIR: str = os.path.dirname(os.path.abspath(__file__))


def _load_config() -> dict[str, Any]:
    """Load config.yaml from the project root."""
    cfg_path = os.path.join(BASE_DIR, "config.yaml")
    with open(cfg_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


CFG: dict[str, Any] = _load_config()

# Heatmap bin configuration (from config.yaml)
REC_BINS: list[int] = CFG["heatmap"]["recency_bins"]
REC_LABELS: list[str] = CFG["heatmap"]["recency_labels"]
MON_BINS: list[int] = CFG["heatmap"]["monetary_bins"]
MON_LABELS: list[str] = CFG["heatmap"]["monetary_labels"]


@st.cache_data(ttl=86400)
def load_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load scored RFM data and segment summary CSVs.

    Returns:
        Tuple of (rfm_scored DataFrame, segment_summary DataFrame).
    """
    rfm = pd.read_csv(os.path.join(BASE_DIR, "data", "rfm_scored.csv"))
    seg = pd.read_csv(os.path.join(BASE_DIR, "data", "segment_summary.csv"))
    seg["_ord"] = seg["Segment"].map({s: i for i, s in enumerate(SEG_ORDER)})
    seg = seg.sort_values("_ord").drop(columns="_ord")
    return rfm, seg


@st.cache_data
def to_csv(df: pd.DataFrame) -> bytes:
    """Encode a DataFrame as UTF-8 CSV bytes for download."""
    return df.to_csv(index=False).encode("utf-8")


rfm_full, seg_summary = load_data()

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown(f"""
    <div style="padding: 0.5rem 0 1.5rem;">
      <div style="font-size:1.1rem; font-weight:600; color:{WHITE}; letter-spacing:-0.01em;">◈ Segmentation</div>
      <div style="font-size:0.75rem; color:{MUTED}; margin-top:2px;">Customer Intelligence Dashboard</div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown(f'<div class="section-label">Filter Segments</div>', unsafe_allow_html=True)

    selected_segments = st.multiselect(
        "Segments",
        options=SEG_ORDER,
        default=SEG_ORDER,
        label_visibility="collapsed",
    )

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(f'<div class="section-label">RFM Score Range</div>', unsafe_allow_html=True)

    score_min, score_max = int(rfm_full["RFM_Score"].min()), int(rfm_full["RFM_Score"].max())
    score_range = st.slider(
        "RFM Score",
        min_value=score_min,
        max_value=score_max,
        value=(score_min, score_max),
        label_visibility="collapsed",
    )

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(f'<div class="section-label">Monetary Filter (£)</div>', unsafe_allow_html=True)

    mon_max = int(rfm_full["Monetary"].max())
    monetary_range = st.slider(
        "Monetary",
        min_value=0,
        max_value=mon_max,
        value=(0, mon_max),
        label_visibility="collapsed",
    )

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(f'<div class="section-label">Customer Lookup</div>', unsafe_allow_html=True)
    customer_search = st.text_input("Customer ID", placeholder="e.g. 14688", label_visibility="collapsed")

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown(f'<div class="section-label">Segment Legend</div>', unsafe_allow_html=True)
    for seg_name, color in SEG_COLORS.items():
        st.markdown(f"""
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px;">
          <div style="width:8px;height:8px;border-radius:50%;background:{color};flex-shrink:0;"></div>
          <span style="font-size:0.8rem;color:{MUTED};">{seg_name}</span>
        </div>
        """, unsafe_allow_html=True)

# ── Apply filters ─────────────────────────────────────────────────────────────
rfm = rfm_full[
    rfm_full["Segment"].isin(selected_segments) &
    rfm_full["RFM_Score"].between(score_range[0], score_range[1]) &
    rfm_full["Monetary"].between(monetary_range[0], monetary_range[1])
].copy()

seg_filtered = seg_summary[seg_summary["Segment"].isin(selected_segments)].copy()

# ── Empty state guard ─────────────────────────────────────────────────────────
if rfm.empty or not selected_segments:
    st.warning("No customers match the current filters. Try broadening your selection.")
    st.stop()

# ── Page header ───────────────────────────────────────────────────────────────
col_title, col_meta = st.columns([3, 1])
with col_title:
    st.markdown(f"""
    <div class="page-title">Customer Segmentation Analysis</div>
    <div class="page-subtitle">RFM Analysis · K-Means Clustering · {rfm['CustomerID'].nunique():,} customers in view</div>
    """, unsafe_allow_html=True)
with col_meta:
    st.markdown(f"""
    <div style="text-align:right;padding-top:0.4rem;">
      <span style="font-size:0.72rem;color:{MUTED};font-family:'DM Mono',monospace;">
        ONLINE RETAIL DATASET
      </span>
    </div>
    """, unsafe_allow_html=True)

st.markdown("<div style='margin-top:1.5rem;'></div>", unsafe_allow_html=True)

# ── KPI Cards ─────────────────────────────────────────────────────────────────
k1, k2, k3, k4, k5 = st.columns(5)

kpi_defs = [
    ("Total Customers",    f"{rfm['CustomerID'].nunique():,}",         "", GREEN),
    ("Total Revenue",      f"£{rfm['Monetary'].sum()/1e6:.1f}M",       "", TEAL),
    ("Avg Ticket Size",    f"£{rfm['Monetary'].mean():,.0f}",          "", BLUE),
    ("Avg Recency",        f"{rfm['Recency'].mean():.0f}d",            "", AMBER),
    ("Avg Frequency",      f"{rfm['Frequency'].mean():.1f}",           "", RED),
]

for col, (label, value, delta, color) in zip([k1,k2,k3,k4,k5], kpi_defs):
    with col:
        st.markdown(f"""
        <div class="kpi-card">
          <div class="kpi-accent" style="background:{color};"></div>
          <div class="kpi-label">{label}</div>
          <div class="kpi-value">{value}</div>
          <div class="kpi-delta">{delta}</div>
        </div>
        """, unsafe_allow_html=True)

st.markdown("<div style='margin-top:2rem;'></div>", unsafe_allow_html=True)

# ── Tabs ──────────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs(["  Overview  ", "  Segment Deep Dive  ", "  Customer Explorer  "])


# ════════════════════════════════════════════════════════════════════════════
# TAB 1 — OVERVIEW
# ════════════════════════════════════════════════════════════════════════════
with tab1:
    st.markdown("<div style='margin-top:1.2rem;'></div>", unsafe_allow_html=True)

    col_left, col_right = st.columns([1, 1], gap="large")

    with col_left:
        st.markdown(f'<div class="section-label">Customer Count by Segment</div>', unsafe_allow_html=True)

        total_customers = seg_filtered["Customers"].sum()
        fig_bar = go.Figure(go.Bar(
            x=seg_filtered["Customers"].values,
            y=seg_filtered["Segment"].values,
            orientation="h",
            marker_color=[SEG_COLORS.get(s, MUTED) for s in seg_filtered["Segment"]],
            marker_line_width=0,
            text=[f'  {int(c):,}  ({c/total_customers*100:.1f}%)' for c in seg_filtered["Customers"]],
            textposition="outside",
            textfont=dict(size=11, color=WHITE),
            showlegend=False,
            hovertemplate="<b>%{y}</b><br>Customers: %{x:,}<extra></extra>",
        ))
        fig_bar.update_layout(
            **PLOT_LAYOUT,
            margin=dict(l=10, r=10, t=36, b=10),
            height=260,
            showlegend=False,
            yaxis=dict(categoryorder="array", categoryarray=SEG_ORDER[::-1],
                       gridcolor="rgba(0,0,0,0)", linecolor=NAVY_BORDER, tickfont=dict(size=11)),
            xaxis=dict(gridcolor=NAVY_BORDER, showticklabels=False, linecolor="rgba(0,0,0,0)"),
            bargap=0.35,
        )
        st.plotly_chart(fig_bar, use_container_width=True, config={"displayModeBar": False})

    with col_right:
        st.markdown(f'<div class="section-label">Revenue Share by Segment</div>', unsafe_allow_html=True)

        fig_donut = go.Figure(go.Pie(
            labels=seg_filtered["Segment"],
            values=seg_filtered["Total_Revenue"],
            hole=0.62,
            marker=dict(
                colors=[SEG_COLORS.get(s, MUTED) for s in seg_filtered["Segment"]],
                line=dict(color=NAVY, width=2),
            ),
            textinfo="percent",
            textfont=dict(size=11, color=WHITE),
            hovertemplate="<b>%{label}</b><br>Revenue: £%{value:,.0f}<br>Share: %{percent}<extra></extra>",
        ))
        total_rev = rfm["Monetary"].sum()
        fig_donut.add_annotation(
            text=f"£{total_rev/1000:.0f}k",
            x=0.5, y=0.52, font=dict(size=20, color=WHITE, family="DM Sans"), showarrow=False,
        )
        fig_donut.add_annotation(
            text="total revenue",
            x=0.5, y=0.42, font=dict(size=11, color=MUTED, family="DM Sans"), showarrow=False,
        )
        fig_donut.update_layout(**PLOT_LAYOUT, height=260, showlegend=False, margin=dict(l=0,r=0,t=36,b=0))
        st.plotly_chart(fig_donut, use_container_width=True, config={"displayModeBar": False})

    st.markdown("<hr>", unsafe_allow_html=True)

    st.markdown(f'<div class="section-label">Customer Density - Recency vs Monetary</div>', unsafe_allow_html=True)

    rec_bins = REC_BINS + [rfm["Recency"].max() + 1]
    if rec_bins[-1] <= rec_bins[-2]:
        rec_bins[-1] = rec_bins[-2] + 1
    rec_labels = REC_LABELS

    mon_bins = MON_BINS + [rfm["Monetary"].max() + 1]
    if mon_bins[-1] <= mon_bins[-2]:
        mon_bins[-1] = mon_bins[-2] + 1
    mon_labels = MON_LABELS

    heat_df = rfm.copy()
    heat_df["Recency_Band"] = pd.cut(heat_df["Recency"], bins=rec_bins, labels=rec_labels, right=True)
    heat_df["Monetary_Band"] = pd.cut(heat_df["Monetary"], bins=mon_bins, labels=mon_labels, right=True)

    heat_data = heat_df.groupby(["Monetary_Band", "Recency_Band"], observed=False).size().unstack(fill_value=0)
    heat_data = heat_data.reindex(index=mon_labels, columns=rec_labels, fill_value=0)

    text_vals = heat_data.values.astype(int).astype(str)

    fig_heat = go.Figure(data=go.Heatmap(
        z=heat_data.values,
        x=rec_labels,
        y=mon_labels,
        colorscale="Plasma",
        showscale=True,
        text=text_vals,
        texttemplate="%{text}",
    ))
    fig_heat.update_layout(
        **PLOT_LAYOUT,
        margin=dict(l=10, r=10, t=36, b=10),
        height=400,
        xaxis=dict(**AXIS_DEFAULTS, title="Recency (days since last purchase)"),
        yaxis=dict(**AXIS_DEFAULTS, title="Monetary Value (£)", categoryorder="array", categoryarray=mon_labels[::-1]),
    )
    st.plotly_chart(fig_heat, use_container_width=True, config={"displayModeBar": False})


# ════════════════════════════════════════════════════════════════════════════
# TAB 2 — SEGMENT DEEP DIVE
# ════════════════════════════════════════════════════════════════════════════
with tab2:
    st.markdown("<div style='margin-top:1.2rem;'></div>", unsafe_allow_html=True)

    active_seg = st.selectbox(
        "Select segment to analyse",
        options=[s for s in SEG_ORDER if s in selected_segments],
        label_visibility="collapsed",
    )

    seg_data = rfm[rfm["Segment"] == active_seg]
    seg_color = SEG_COLORS.get(active_seg, MUTED)

    seg_row_matches = seg_summary[seg_summary["Segment"] == active_seg]
    if seg_row_matches.empty:
        st.warning(f"Segment '{active_seg}' not found in summary data.")
        st.stop()
    seg_row = seg_row_matches.iloc[0]

    st.markdown("<div style='margin-top:0.8rem;'></div>", unsafe_allow_html=True)

    d1, d2, d3, d4, d5 = st.columns(5)
    deep_kpis = [
        ("Total Customers",  f"{int(seg_row['Customers']):,}",    ""),
        ("Avg Recency",      f"{seg_row['Avg_Recency']:.0f}d",    ""),
        ("Avg Frequency",    f"{seg_row['Avg_Frequency']:.1f}",   ""),
        ("Avg Spend Rate",   f"£{seg_row['Avg_Monetary']:,.0f}",  ""),
        ("Revenue Share",    f"{seg_row['Revenue_Pct']:.1f}%",    ""),
    ]
    for dcol, (lbl, val, delta) in zip([d1,d2,d3,d4,d5], deep_kpis):
        with dcol:
            st.markdown(f"""
            <div class="kpi-card">
              <div class="kpi-accent" style="background:{seg_color};"></div>
              <div class="kpi-label">{lbl}</div>
              <div class="kpi-value">{val}</div>
              <div class="kpi-delta">{delta}</div>
            </div>
            """, unsafe_allow_html=True)

    st.markdown("<div style='margin-top:1.5rem;'></div>", unsafe_allow_html=True)

    st.markdown(f'<div class="section-label">RFM Distribution - {active_seg} vs Full Portfolio</div>', unsafe_allow_html=True)

    bc1, bc2, bc3 = st.columns(3, gap="large")
    for col_plot, metric, label in zip(
        [bc1, bc2, bc3],
        ["Recency", "Frequency", "Monetary"],
        ["Days Since Last Purchase", "Number of Orders", "Total Spend (£)"]
    ):
        with col_plot:
            fig_box = go.Figure()
            fig_box.add_trace(go.Box(
                y=rfm_full[metric],
                name="All Customers",
                marker_color=MUTED,
                line_color=MUTED,
                fillcolor=hex_to_rgba(MUTED, 0.13),
                boxmean=True,
                showlegend=False,
                hoverinfo="y",
            ))
            fig_box.add_trace(go.Box(
                y=seg_data[metric],
                name=active_seg,
                marker_color=seg_color,
                line_color=seg_color,
                fillcolor=hex_to_rgba(seg_color, 0.2),
                boxmean=True,
                showlegend=False,
                hoverinfo="y",
            ))
            fig_box.update_layout(
                **PLOT_LAYOUT,
                height=250,
                showlegend=False,
                title=dict(text=label, font=dict(size=11, color=MUTED), x=0),
                xaxis=dict(tickvals=[0,1], ticktext=["All", active_seg],
                           gridcolor="rgba(0,0,0,0)", linecolor=NAVY_BORDER),
                yaxis=dict(**AXIS_DEFAULTS),
                margin=dict(l=10,r=10,t=40,b=10),
            )
            st.plotly_chart(fig_box, use_container_width=True, config={"displayModeBar": False})

    st.markdown("<hr>", unsafe_allow_html=True)

    RECOMMENDATIONS = {
        "Champions": {
            "priority": "PROTECT",
            "color": GREEN,
            "actions": [
                "Launch a VIP loyalty tier with exclusive early access and perks",
                "Personalised thank-you communications and milestone rewards",
                "Referral programme - leverage their advocacy to acquire similar customers",
                "Monitor closely for any recency slip; trigger re-engagement immediately",
            ],
            "metric": "Champion retention rate >= 95% month-over-month",
        },
        "Loyal Customers": {
            "priority": "GROW",
            "color": TEAL,
            "actions": [
                "Frequency upsell - bundle deals and auto-replenishment nudges",
                "Targeted cross-sell based on purchase category history",
                "Bi-weekly personalised email cadence with curated recommendations",
                "Identify top 20% most likely to become Champions; give them targeted push",
            ],
            "metric": "Move 15-20% of Loyal customers into Champions tier per quarter",
        },
        "Potential Loyalists": {
            "priority": "CONVERT",
            "color": BLUE,
            "actions": [
                "Second-purchase incentive within 30 days of first order",
                "Onboarding journey - showcase product range and brand story",
                "Post-purchase review request to increase engagement",
                "Retargeting ads and email within 2 weeks of last visit",
            ],
            "metric": "Second-purchase rate >= 40% within 60 days of acquisition",
        },
        "At Risk": {
            "priority": "WIN BACK",
            "color": AMBER,
            "actions": [
                "3-step win-back email sequence over 21 days (soft -> offer -> final)",
                '"We miss you" discount offer (10-15%) to trigger re-engagement',
                "Short NPS survey to understand reason for disengagement",
                "Prioritise customers with Frequency >= 3 for highest ROI on re-engagement",
            ],
            "metric": "Win-back rate >= 30% of targeted At Risk customers per campaign",
        },
        "Lost / Churned": {
            "priority": "ASSESS ROI",
            "color": RED,
            "actions": [
                "One-time deep-discount reactivation campaign (20-25%)",
                "Target only top 25% by historical monetary value - rest are not cost-effective",
                "Sunset low-value customers from active CRM lists to reduce cost",
                "Use profile data to improve retention signals for other segments",
            ],
            "metric": "Reactivation rate >= 15% - only for customers with LTV > £200",
        },
    }

    rec = RECOMMENDATIONS.get(active_seg, {})
    if rec:
        st.markdown(f'<div class="section-label">Recommended Actions</div>', unsafe_allow_html=True)
        rcol1, rcol2 = st.columns([1, 2], gap="large")
        with rcol1:
            st.markdown(f"""
            <div class="kpi-card" style="height:100%;">
              <div class="kpi-accent" style="background:{rec['color']};"></div>
              <div class="kpi-label">Priority</div>
              <div style="font-size:1.4rem;font-weight:600;color:{rec['color']};margin-bottom:1rem;">
                {rec['priority']}
              </div>
              <div class="kpi-label">Success Metric</div>
              <div style="font-size:0.82rem;color:{WHITE};line-height:1.5;">
                {rec['metric']}
              </div>
            </div>
            """, unsafe_allow_html=True)
        with rcol2:
            actions_html = "".join([
                f'<div style="display:flex;gap:10px;align-items:flex-start;margin-bottom:10px;">'
                f'<div style="width:4px;height:4px;border-radius:50%;background:{rec["color"]};margin-top:7px;flex-shrink:0;"></div>'
                f'<div style="font-size:0.85rem;color:{WHITE};line-height:1.55;">{a}</div></div>'
                for a in rec["actions"]
            ])
            st.markdown(f"""
            <div class="kpi-card" style="height:100%;">
              <div class="kpi-accent" style="background:{rec['color']};"></div>
              <div class="kpi-label">Actions</div>
              {actions_html}
            </div>
            """, unsafe_allow_html=True)


# ════════════════════════════════════════════════════════════════════════════
# TAB 3 — CUSTOMER EXPLORER
# ════════════════════════════════════════════════════════════════════════════
with tab3:
    st.markdown("<div style='margin-top:1.2rem;'></div>", unsafe_allow_html=True)

    if customer_search.strip():
        try:
            cid = int(customer_search.strip())
            match = rfm_full[rfm_full["CustomerID"] == cid]
            if not match.empty:
                row = match.iloc[0]
                cseg = row["Segment"]
                ccolor = SEG_COLORS.get(cseg, MUTED)

                st.markdown(f'<div class="section-label">Customer Profile - ID {cid}</div>', unsafe_allow_html=True)
                cc1, cc2, cc3, cc4, cc5 = st.columns(5)
                profile_kpis = [
                    ("Segment",    f"{SEG_ICONS.get(cseg,'')} {cseg}", "", ccolor),
                    ("Recency",    f"{int(row['Recency'])}d",           "days ago",        ccolor),
                    ("Frequency",  f"{int(row['Frequency'])}",          "total orders",    ccolor),
                    ("Monetary",   f"£{row['Monetary']:,.0f}",          "lifetime value",  ccolor),
                    ("RFM Score",  f"{int(row['RFM_Score'])} / 15",     f"R{row['R_Score']} F{row['F_Score']} M{row['M_Score']}", ccolor),
                ]
                for pcol, (lbl, val, delta, pc) in zip([cc1,cc2,cc3,cc4,cc5], profile_kpis):
                    with pcol:
                        st.markdown(f"""
                        <div class="kpi-card">
                          <div class="kpi-accent" style="background:{pc};"></div>
                          <div class="kpi-label">{lbl}</div>
                          <div class="kpi-value" style="font-size:1.2rem;">{val}</div>
                          <div class="kpi-delta">{delta}</div>
                        </div>
                        """, unsafe_allow_html=True)
                st.markdown("<div style='margin-top:1rem;'></div>", unsafe_allow_html=True)
            else:
                st.warning(f"Customer ID {cid} not found in dataset.")
        except ValueError:
            st.warning("Enter a valid numeric Customer ID.")

    st.markdown(f'<div class="section-label">Customer Data Table - {len(rfm):,} records</div>', unsafe_allow_html=True)

    col_sort, col_order, col_spacer = st.columns([2, 2, 4])
    with col_sort:
        sort_col = st.selectbox(
            "Sort by",
            options=["RFM_Score", "Monetary", "Recency", "Frequency", "CustomerID"],
            label_visibility="collapsed",
        )
    with col_order:
        sort_asc = st.selectbox(
            "Order",
            options=["Descending", "Ascending"],
            label_visibility="collapsed",
        ) == "Ascending"

    display_df = rfm.sort_values(sort_col, ascending=sort_asc)[
        ["CustomerID", "Segment", "Recency", "Frequency", "Monetary",
         "R_Score", "F_Score", "M_Score", "RFM_Score"]
    ].rename(columns={
        "CustomerID": "Customer ID",
        "R_Score": "R", "F_Score": "F", "M_Score": "M",
        "RFM_Score": "RFM Score",
    })
    display_df["Monetary"] = display_df["Monetary"].round(2)

    st.dataframe(
        display_df,
        use_container_width=True,
        height=400,
        hide_index=True,
    )

    st.markdown("<div style='margin-top:0.8rem;'></div>", unsafe_allow_html=True)

    csv_bytes = to_csv(display_df)
    st.download_button(
        label="Download filtered data as CSV",
        data=csv_bytes,
        file_name="customer_segments_filtered.csv",
        mime="text/csv",
    )

    st.markdown("<br>", unsafe_allow_html=True)

    st.markdown(f'<div class="section-label">RFM Score Distribution</div>', unsafe_allow_html=True)

    fig_hist = go.Figure()
    for seg_name in SEG_ORDER:
        if seg_name not in selected_segments:
            continue
        subset = rfm[rfm["Segment"] == seg_name]
        fig_hist.add_trace(go.Histogram(
            x=subset["RFM_Score"],
            name=seg_name,
            marker_color=SEG_COLORS.get(seg_name, MUTED),
            opacity=0.8,
            xbins=dict(start=3, end=15, size=1),
            hovertemplate=f"<b>{seg_name}</b><br>Score: %{{x}}<br>Count: %{{y}}<extra></extra>",
        ))
    fig_hist.update_layout(
        **PLOT_LAYOUT,
        barmode="stack",
        height=220,
        xaxis=dict(**AXIS_DEFAULTS, title="RFM Score (3-15)", dtick=1),
        yaxis=dict(**AXIS_DEFAULTS, title="Customer Count"),
        legend=dict(bgcolor="rgba(0,0,0,0)", bordercolor=NAVY_BORDER, borderwidth=1,
                    font=dict(size=11, color=WHITE),
                    orientation="h", yanchor="bottom", y=1.02, xanchor="left", x=0),
        margin=dict(l=10, r=10, t=50, b=10),
    )
    st.plotly_chart(fig_hist, use_container_width=True, config={"displayModeBar": False})
